INSERT INTO asmat(first_name, last_name, email, street_no, street, postal_code, city, adherent) VALUES('Ekram', 'ABAAKIL', '', '54', 'Rue de Gognies chaussée', '59600', 'MAUBEUGE', true);
INSERT INTO asmat(first_name, last_name, email, street_no, street, postal_code, city, adherent) VALUES('Hadjira', 'ABBAKIL', 'Oumiaya@hotmail.fr', '2', 'Rue Lucien Bouillot', '59720', 'LOUVROIL', true);
INSERT INTO asmat(first_name, last_name, email, street_no, street, postal_code, city, adherent) VALUES('Fatima', 'ACHOUR', '', '18', 'Rue Jean Racinne', '59600', 'MAUBEUGE', true);
INSERT INTO asmat(first_name, last_name, email, street_no, street, postal_code, city, adherent) VALUES('Sabine', 'ADAM', 'Sabineadam03@gmail.com', '27', 'Rue des Tries', '59330', 'HAUTMONT', true);
INSERT INTO asmat(first_name, last_name, email, street_no, street, postal_code, city, adherent) VALUES('Latifa', 'AIT BELLA', '', '23', 'Imm. De Dion Bouton rue de Grévaux', '59600', 'MAUBEUGE', true);
INSERT INTO asmat(first_name, last_name, email, street_no, street, postal_code, city, adherent) VALUES('Aïcha', 'AIT LAMKADEM', 'Aicha.aitlamkadem@laposte.net', '18', 'Rue Jeanne Jugan', '59600', 'MAUBEUGE', true);
INSERT INTO asmat(first_name, last_name, email, street_no, street, postal_code, city, adherent) VALUES('Sonia', 'ANSEL', 'Sonia.ansel@orange.fr', '9', 'Rue du Transvaal', '59131', 'ROUSIES', true);
INSERT INTO asmat(first_name, last_name, email, street_no, street, postal_code, city, adherent) VALUES('Nicole', 'ANTOLINI', 'Michel.antolini@neuf.fr', '26', 'Rue Kennedy', '59600', 'MAUBEUGE', true);
INSERT INTO asmat(first_name, last_name, email, street_no, street, postal_code, city, adherent) VALUES('Samara', 'ATMANI', 'Samara.atmani@gmail.com', '72', 'Rue André Messager', '59460', 'JEUMONT', true);
INSERT INTO asmat(first_name, last_name, email, street_no, street, postal_code, city, adherent) VALUES('Johanna', 'ATTARY', 'Attarynassima@live.fr', '10', 'Place Poincaré', '59168', 'BOUSSOIS', true);
INSERT INTO asmat(first_name, last_name, email, street_no, street, postal_code, city, adherent) VALUES('Tracy', 'AUGUET', 'T.auguet59@gmail.com', '3', 'A rue du 145ème RI Immeuble Colonnel Martin La Joyeuse 1', '59600', 'MAUBEUGE', true);
INSERT INTO asmat(first_name, last_name, email, street_no, street, postal_code, city, adherent) VALUES('Aurore', 'BADARD', 'Aurorebadard@yahoo.fr', '24', 'B rue Léo Lagrange', '59460', 'JEUMONT', true);
INSERT INTO asmat(first_name, last_name, email, street_no, street, postal_code, city, adherent) VALUES('Sandrine', 'BAELDE', 'Sandrine.baelde@sfr.fr', '209', 'Rue du Fort', '59680', 'CERFONTAINE', true);
INSERT INTO asmat(first_name, last_name, email, street_no, street, postal_code, city, adherent) VALUES('Faroudja', 'BAHLOUL', '', '70', 'Avenue Nicolas Boileau', '59600', 'MAUBEUGE', true);
INSERT INTO asmat(first_name, last_name, email, street_no, street, postal_code, city, adherent) VALUES('Corinne', 'BANSE', '', '20', 'Rue Gabriel Péri', '59168', 'BOUSSOIS', true);
INSERT INTO asmat(first_name, last_name, email, street_no, street, postal_code, city, adherent) VALUES('Christelle', 'BARZIN', 'Michel.barzin@sfr.fr', '10', 'Rue des frères Lumière', '59600', 'MAUBEUGE', true);
INSERT INTO asmat(first_name, last_name, email, street_no, street, postal_code, city, adherent) VALUES('Christelle', 'BASTIEN', 'Michael.bastien@sfr.fr', '2', 'Résidence Joffre entrée Vaux', '59460', 'JEUMONT', true);
INSERT INTO asmat(first_name, last_name, email, street_no, street, postal_code, city, adherent) VALUES('Jocelyne', 'BATARDY', 'Clement.batardy@laposte.net', '13', 'Rue des Martyrs', '59570', 'HOUDAIN LEZ BAVAY', true);
INSERT INTO asmat(first_name, last_name, email, street_no, street, postal_code, city, adherent) VALUES('Emmanuelle', 'BAUDOUIN', '', '2', 'Rue Faidherbe', '59164', 'MARPENT', true);
INSERT INTO asmat(first_name, last_name, email, street_no, street, postal_code, city, adherent) VALUES('Marie', 'BAUDET', 'Baudetgilliard.marie@gmail.com', '121', 'Rue d''Ostergnies', '59680', 'CERFONTAINE', true);
INSERT INTO asmat(first_name, last_name, email, street_no, street, postal_code, city, adherent) VALUES('Véronique', 'BAYART', '', '78', 'Rue de La Cavée', '59330', 'HAUTMONT', true);
INSERT INTO asmat(first_name, last_name, email, street_no, street, postal_code, city, adherent) VALUES('Fatima', 'BEHDENNA', 'Zonga73@gmail.com', '57', 'Rue Sainte Emilie', '59600', 'MAUBEUGE', true);
INSERT INTO asmat(first_name, last_name, email, street_no, street, postal_code, city, adherent) VALUES('Fouzia', 'BENATMANE', 'Mouloud0059@gmail.com', '18', 'Rue du Colonel Dereppe', '59330', 'HAUTMONT', true);
INSERT INTO asmat(first_name, last_name, email, street_no, street, postal_code, city, adherent) VALUES('Lynda', 'BENBELKACEM', 'Louisemina3@yahoo.fr', '12', 'Rue René Fonck', '59600', 'MAUBEUGE', true);
INSERT INTO asmat(first_name, last_name, email, street_no, street, postal_code, city, adherent) VALUES('Farida', 'BENSOLTANE', 'Farida.bahraoui@gmail.com', '16', 'Cité André Lemoine', '59330', 'NEUF MESNIL', true);
INSERT INTO asmat(first_name, last_name, email, street_no, street, postal_code, city, adherent) VALUES('Brigitte', 'BESSIERES', 'Brigittebessieres@hotmail.com', '41', 'Rue des Anciens d''AFN Résidence Bérénice', '59570', 'BAVAY', true);
INSERT INTO asmat(first_name, last_name, email, street_no, street, postal_code, city, adherent) VALUES('Véronique', 'BETH', 'Freddy.beth@orange.fr', '389', 'Chemin de la Rosière', '59144', 'AMFROIPRET', true);
INSERT INTO asmat(first_name, last_name, email, street_no, street, postal_code, city, adherent) VALUES('Roselyne', 'BIDOIS', 'Jean-claude.bidois@wanadoo.fr', '1129', 'Rue du Fort', '59680', 'FERRIERE LA GRANDE', true);
INSERT INTO asmat(first_name, last_name, email, street_no, street, postal_code, city, adherent) VALUES('Sabine', 'BLASUTTO', '', '11', 'Rue d''Elesmes', '59600', 'MAIRIEUX', true);
INSERT INTO asmat(first_name, last_name, email, street_no, street, postal_code, city, adherent) VALUES('Bénédicte', 'BLEUSE', '', '97', 'Rue de Keyworth', '59750', 'FEIGNIES', true);
INSERT INTO asmat(first_name, last_name, email, street_no, street, postal_code, city, adherent) VALUES('Sabine', 'BLONDIAU', 'Sabine.blondiau@sfr.fr', '34', 'Rue des Roblins', '59600', 'VILLERS SIRE NICOLE', true);
INSERT INTO asmat(first_name, last_name, email, street_no, street, postal_code, city, adherent) VALUES('Valérie', 'BOLTZ', 'Boltzvalerie74@free.fr', '12', 'Rue Béranger', '59330', 'HAUTMONT', true);
INSERT INTO asmat(first_name, last_name, email, street_no, street, postal_code, city, adherent) VALUES('Marie Line', 'BONVISSUTO', 'Marie-line.bonvissuto@orange.fr', '741', 'Rue Grand Chemin', '59680', 'OBRECHIES', true);
INSERT INTO asmat(first_name, last_name, email, street_no, street, postal_code, city, adherent) VALUES('Catherine', 'BOROWIAK', 'Fredybor@aol.com', '38', 'Rue Gilbert Lanthier', '59168', 'BOUSSOIS', true);
INSERT INTO asmat(first_name, last_name, email, street_no, street, postal_code, city, adherent) VALUES('Madeleine', 'BORTZMEYER', 'Bortzmeyersylvain1969@gmail.com', '58', 'Rue René Fourchet', '59245', 'RECQUIGNIES', true);
INSERT INTO asmat(first_name, last_name, email, street_no, street, postal_code, city, adherent) VALUES('Aîcha', 'BOUBBICHE', 'Ali.boubbiche59@orange.fr', '12', 'Rue de la chapelle', '59600', 'ELESMES', true);
INSERT INTO asmat(first_name, last_name, email, street_no, street, postal_code, city, adherent) VALUES('Marie Paule', 'BOUILLON', '', '40', 'Rue Robert Gilbert', '59680', 'FERRIERE LA PETITE', true);
INSERT INTO asmat(first_name, last_name, email, street_no, street, postal_code, city, adherent) VALUES('Nathalie', 'BOUNOUA', 'Selma0874@outlook.fr', '64', 'Rue des Ecoles', '59600', 'MAUBEUGE', true);
INSERT INTO asmat(first_name, last_name, email, street_no, street, postal_code, city, adherent) VALUES('Maryse', 'BOUQUENIAUX', 'Maryse.bouqueniaux@laposte.net', '9', 'Impasse des Peupliers', '59600', 'ASSEVENT', true);
INSERT INTO asmat(first_name, last_name, email, street_no, street, postal_code, city, adherent) VALUES('Muriel', 'BOURDIN', '', '5', 'Rue du Pont de Pierre', '59600', 'ELESMES', true);
INSERT INTO asmat(first_name, last_name, email, street_no, street, postal_code, city, adherent) VALUES('Mandine', 'BOURGEOIS', 'Julien.sequeira@sfr.fr', '61', 'Route de Mons', '59600', 'MAUBEUGE', true);
INSERT INTO asmat(first_name, last_name, email, street_no, street, postal_code, city, adherent) VALUES('Denise', 'BOURGUELLE', 'Denise.bourguelle@sfr.fr', '15', 'Rés. Du Tir à l''Arc', '59149', 'COUSOLRE', true);
INSERT INTO asmat(first_name, last_name, email, street_no, street, postal_code, city, adherent) VALUES('Rachida', 'BOUSHIM', 'Sali.hate@hotmail.fr', '1', 'A rue de la Paix', '59330', 'NEUF MESNIL', true);
INSERT INTO asmat(first_name, last_name, email, street_no, street, postal_code, city, adherent) VALUES('Nathalie', 'BOUTTEAU', 'Coquelicotnat@aol.com', '850', 'Route de la Longueville', '59570', 'AUDIGNIES', true);
INSERT INTO asmat(first_name, last_name, email, street_no, street, postal_code, city, adherent) VALUES('Fatima', 'BOUYADOU', 'Fatimaedar@hotmail.fr', '39', 'Rue des Hauts fourneaux', '59600', 'MAUBEUGE', true);
INSERT INTO asmat(first_name, last_name, email, street_no, street, postal_code, city, adherent) VALUES('Laurie', 'BREL', '', '68', 'Avenue Juliot Curie', '59620', 'AULNOYE AYMERIES', true);
INSERT INTO asmat(first_name, last_name, email, street_no, street, postal_code, city, adherent) VALUES('Muriel', 'BRILLET', 'Murielbrillet@orange.fr', '14', 'Rue de la résistance Rés. De l''atrium', '59570', 'BAVAY', true);
INSERT INTO asmat(first_name, last_name, email, street_no, street, postal_code, city, adherent) VALUES('Josiane', 'BRUNI', 'Michel.bruni@wanadoo.fr', '55', 'Rue de Mairieux', '59600', 'MAUBEUGE', true);
INSERT INTO asmat(first_name, last_name, email, street_no, street, postal_code, city, adherent) VALUES('Catherine', 'BUCHIN', '', '20', 'Rue Albert Mathieu', '59600', 'VILLERS SIRE NICOLE', true);
INSERT INTO asmat(first_name, last_name, email, street_no, street, postal_code, city, adherent) VALUES('Vanessa', 'BUYLE', '', '43', 'Bis rue Lénine', '59530', 'NEUF MESNIL', true);

INSERT INTO user(username, password)
VALUES ('corentin', '$2a$10$FrWeOhAt9wIhYq56LeOE5.MZoVjT1lgBYhD32dCnemeckL.FLiwfi');